### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ivantree** [skeeks-cms/app-basic#2]
PHP Notice – yii\base\ErrorException

Undefined variable: tree

1. in C:\wamp64\demo.ru\frontend\templates\default\widgets\TreeMenuCmsWidget\menu-top.php

> 
</li>
        <li class="<?= \Yii::$app->request->absoluteUrl == \yii\helpers\Url::home(true) ? 'active' : ''; ?>">
            <a href="<?= \yii\helpers\Url::home(); ?>"><i class="fa fa-home"></i> Главная</a>
        </li>
 
        <? if ($trees = $widget->activeQuery->all()) : ?>
            <? foreach ($trees as $tree) : ?>
                <?= $this->render("_one", [
                    "widget"        => $widget,
                    "model"         => $tree,
                ]); ?>
            <? endforeach; ?>
        <? endif; ?>
 
        <!--<li class="dropdown dropdown-aux animate-click" data-animate-in="animated bounceInUp" data-animate-out="animated fadeOutDown" style="z-index:500;">
            <a href="#" class="dropdown-form-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-user animate-wr">
                <li id="dropdownForm">
                    <div class="dropdown-form">

**Comment by pavlm** [comment]
Тоже получил эту ошибку. Чтобы исправить надо включить короткие теги:
`short_open_tag = On`
